---
all:
    vars:
        ansible_user: appadmin
        ansible_ssh_private_key_file: the-key
    children:
        http-servers:
            hosts:
                httpserver.jenkins_mynetwork:
        app-servers:
            hosts:
                websphere.jenkins_mynetwork: