- name: Restart Liberty Server
  find:
    paths: "{{ LIBERTY_PROFILE_PATH }}"
    file_type: directory
    recurse: no
    patterns: '*{{ jvm_search_pattern }}*'
  register: findresult
- name: Show whoami result
  debug:
    msg: "{{ findresult }}"
