- name: Restart Liberty Server
  shell: "echo 'Write script for finding and restarting JVMs with name containing {{ pattern }}' "
  register: whoamiresult
- name: Show whoami result
  debug:
    msg: "{{ whoamiresult.stdout }}"
