- name: Restart Liberty Server
  find:
    paths: "{{ LIBERTY_PROFILE_PATH }}/servers"
    file_type: directory
    recurse: no
    patterns: '*{{ jvm_search_pattern }}*'
  register: findresult
- name: Show whoami result
  debug:
    msg: "{{ item | relpath(LIBERTY_PROFILE_PATH/servers) }}"
  with_items: "{{ findresult.files|map(attribute='path')|list }}"
