- name: Extract IBM Liberty Files
  unarchive:
    src: "{{ LIBERTY_ARCHIVE_FILE }}"
    dest: "{{ LIBERTY_INSTALL_PATH }}"
    remote_src: yes
    creates: "{{ LIBERTY_INSTALL_PATH }}/IBM/WebSphere/Liberty"
  notify: "Liberty Updated"