---
# tasks file for hostname
- name: Execute date function
  shell: date
  register: dateresult
  debug:
    msg: "{{ dateresult.stdout }}"
  when: '(WAS_DEPLOY_NODE is defined and WAS_DEPLOY_NODE==true)'
