---
all:
    vars:
        ansible_user: appadmin
        ansible_ssh_private_key_file: the-key
    children:
        httpservers:
            hosts:
                httpserver.jenkins_mynetwork:
        appservers:
            hosts:
                websphere.jenkins_mynetwork:
                httpserver.jenkins_mynetwork:
