- name: Getting Liberty Version
  shell:
    "{{ LIBERTY_INSTALL_PATH }}/IBM/WebSphere/Liberty/bin/productInfo version"
  register: libertyversion
- name: Display Liberty Version
  debug:
    msg: "{{ libertyversion.stdout_lines }}"
