- name: Getting Java Version
  shell:
    "{{ IBM_JAVA_INSTALL_PATH }}/IBM/java/*/bin/java -version"
  listen: "Java Updated"
  register: javaversion
- name: Display Java Version
  debug:
    msg: "{{ javaversion.stderr_lines }}"
  listen: "Java Updated"
