---
# handlers file for installLiberty
# - name: Getting Java Version
#   shell:
#     "{{ IBM_JAVA_INSTALL_PATH }}/IBM/java/*/bin/java -version"
#   register: javaversion
#   listen: "Java Updated"
# - name: Display Java Version
#   debug:
#     msg: "{{ javaversion.stderr_lines }}"
# listen: "Java Updated"
- name: Java Updated
  include_tasks: handler_ibm_jdk.yml
- name: Getting Liberty Version
  shell:
    "{{ LIBERTY_INSTALL_PATH }}/IBM/WebSphere/Liberty/bin/productInfo version"
  register: libertyversion
  listen: "Liberty Updated"
- name: Display Liberty Version
  debug:
    msg: "{{ libertyversion.stdout_lines }}"
  listen: "Liberty Updated"
