---
# handlers file for installLiberty
- name: Java Updated
  include_tasks: roles/installLiberty/handlers/handler_ibm_jdk.yml
- name: Liberty Updated
  include_tasks: roles/installLiberty/handlers/handler_liberty.yml
