pipeline {
agent { 
        node {
            label 'ansible'
        }
    }
    stages {
        stage('Build') {  
            steps {
                echo "building"
            }
        }
        stage('Deploy to testing') {  
            steps {
                echo "deployed to testing"
            }
        }
        stage('Approval') {  
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    input "Deploy to prod?"
                }
            }
        }
        stage('Deploy to Production') {  
            steps {
                echo "deployed"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}