pipeline {
agent { 
        node {
            label 'ansible'
        }
    }
    environment {
        ANSIBLE_VALUT= credentials('MID_ANSIBLE_VAULT')
    }
  stages {
    stage('Decrypt Private Key') {  
      steps {
          sh """
                echo $ANSIBLE_VALUT > .mysecret
                export ANSIBLE_VAULT_PASSWORD_FILE=.mysecret
                ansible-vault decrypt the-key
                echo "removed the key" > .mysecret
            """
      }
    }
    stage('Run Play') {  
      steps {
          script {
              timeout(time: 10, unit: 'MINUTES') {
                input(id: "Proceed ?", message: "Deploy?", ok: 'Deploy')
              }
          sh """
              export ANSIBLE_HOST_KEY_CHECKING=False
              ansible-playbook -i hosts.yaml ping-play.yaml
            """
      }
    }
  }
    post {
        always {
            cleanWs()
        }
    }
}