- hosts:
    - all
  gather_facts: false
  tasks:
  - name: Execute date function
    shell:
      cmd: date
    register: dateresult
    when: '(WAS_DEPLOY_NODE is defined and WAS_DEPLOY_NODE==true)'
  - name: Show date function result
    debug:
      msg: "{{ dateresult.stdout }}"
    when: '(WAS_DEPLOY_NODE is defined and WAS_DEPLOY_NODE==true)'
  - name: Execute whoami
    shell:
      cmd: whoami
    register: whoamiresult
  - name: Show whoami result
    debug:
      msg: "{{ whoamiresult.stdout }}"
