- hosts:
    - all
  gather_facts: false
  tasks:
  - name: Show date
    shell:
      cmd: |
        date
    register: date_result
  - name: Show date result
    debug:
      msg: "{{ date_result.stdout }}"

  - name: Show whoami
    shell:
      cmd: |
        date
    register: whoami_result
  - name: Show whoami results
    debug:
      msg: "{{ whoami_result.stdout}}"
