- hosts:
    - all
  gather_facts: false
  tasks:
  - name: Exec sh script on Remote Node
    shell:
      cmd: |
        date
        whoami
    register: result

  - name: Show result
    debug:
      msg: "{{ result.stdout }}"
