- hosts:
    - all
  gather_facts: false
  tasks:
  - name: Show date
    shell:
      cmd: |
        date
    register: date_result
  - name: Show whoami
    shell:
      cmd: |
        date
    register: whoami_result

  - name: Show result
    debug:
      msg: "{{ date_result.stdout , whoami_result.stdout}}"
