- name: JVM Actions Playbook
  hosts: "{{ HOSTS }}"
  gather_facts: false
#  vars:
#    - jvm_search_pattern: mw-inst01
#    - jvm_action: stop/start/restart
  vars:
    _allowed_actions:
      - stop
      - start
      - restart
      - status
  pre_tasks:
    - name: Make sure mandatory params exist
      fail:
        msg: "jvm_action variable is not present"
      when: jvm_action is not defined
    - name: Check jvm_action value
      fail:
        msg: "Action Unsupported"
      when: not jvm_action in _allowed_actions
  roles:
    - role: actionJVMByName
