- name: JVM Actions Playbook
  hosts: "{{ HOSTS }}"
  gather_facts: false
#  variables required:
#    - jvm_search_pattern=
#        example:
#           jvm_search_pattern=mw-inst01 will find all JVMs with matching name of *mw-inst01*
#           jvm_search_pattern=* means all JVMs across all WebSphere nodes in the inventory.
#    - action=
#           stop/start/restart/status/thread-dump/heap-dump/core-dump
  vars:
    _allowed_actions:
      - stop
      - start
      - restart
      - status
      - thread-dump
      - heap-dump
      - core-dump
    _not_allowed_search_patterns:
      - ""
      - "/"

  pre_tasks:
    - name: Make sure mandatory params exist
      fail:
        msg: "Variable {{ item }} is not defined"
      when: item not in vars
      with_items:
        - jvm_search_pattern
        - action
    - name: Check jvm_search_pattern value
      fail:
        msg: "jvm_search_pattern Unsupported"
      when: jvm_search_pattern in _not_allowed_search_patterns
    - name: Check action value
      fail:
        msg: "Action Unsupported"
      when: not action in _allowed_actions

  roles:
    - role: actionJVMByName
